from tkinter import Tk, Frame, LEFT, RIGHT, Label, Button
root = Tk()
root.geometry("200x150")
frame = Frame(root)
frame.pack()
leftframe = Frame(root)
leftframe.pack(side=LEFT)
rightframe = Frame(root)
rightframe.pack(side=RIGHT)
label = Label(frame, text="Exercicio tk widget 1")
label.pack()
button1 = Button(leftframe, text="Botão 1")
button1.pack(padx=10, pady=10)
button2 = Button(rightframe, text="Botão 2")
button2.pack(padx=10, pady=10)
button3 = Button(leftframe, text="Botão 3")
button3.pack(padx=10, pady=10)
root.title("Exercicio")
root.mainloop()
