@startuml Acoplamento baixo
class Impressora {
    +imprimir(conteudo: String)
}

class Aplicativo {
    -impressora: Impressora

    +Aplicativo(impressora: Impressora)
    +imprimirDocumento(documento: String)
}

Impressora <|-- Aplicativo: usa 1
@enduml
